version: '3.8'

services:
  rp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rp-be
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: rpuser
      DATABASE_PASSWORD: rppass@123
      DATABASE_DB: rudreshwarproductions
    networks:
      - rp-network

  postgres:
    image: postgres:14
    container_name: rp-postgres
    restart: always
    environment:
      POSTGRES_USER: rpuser
      POSTGRES_PASSWORD: rppass@123
      POSTGRES_DB: rudreshwarproductions
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rp-network

volumes:
  postgres-data:

networks:
  rp-network:
    driver: bridge
